name: Spell checking
on:
  pull_request:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '50 6 * * *'

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 0
    - uses: check-spelling/check-spelling@0.0.5-alpha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        bucket: ssh://git@github.com/jsoref/perl6-doc.git
        project: spelling-data
        timeframe: 1440
